files:
  - source: /app/src/main/res/values/*.xml
    ignore:
      - /**/attrs.xml
      - /**/colors.xml
      - /**/dimens.xml
      - /**/ic_*.xml
      - /**/themes*.xml
      - /**/emotes_*.xml
      - /**/theme_*.xml
      - /**/timeout_*.xml
      - /**/timestamp_*.xml
      - /**/roomstate_*.xml
      - /**/mention_*.xml
      - /**/badges_entry_values.xml
      - /**/styles.xml
      - /**/event_api_timeout_*.xml
    translation: /%original_path%-%android_code%/%original_file_name%
