[versions]
kotlin = "2.4.10"
coroutines = "1.11.0"
serialization = "1.11.0"
datetime = "0.8.0-0.6.x-compat"
immutable = "0.5.1"
ktor = "3.5.2"
coil = "3.5.0"
okhttp = "5.4.0"
ksp = "2.3.11"
koin = "4.2.2"
koin-compiler-plugin = "1.1.0"
about-libraries = "15.0.4"

androidGradlePlugin = "9.3.1"
androidDesugarLibs = "2.1.5"
androidxActivity = "1.13.0"
androidxBrowser = "1.10.0"
androidxConstraintLayout = "2.2.1"
androidxCore = "1.19.0"
androidxEmoji2 = "1.6.0"
androidxExif = "1.4.2"
androidxFragment = "1.8.9"
androidxTransition = "1.7.0"
androidxLifecycle = "2.11.0"
androidxNavigation = "2.9.8"
androidxRecyclerview = "1.4.0"
androidxViewpager2 = "1.1.0"
androidxRoom = "2.8.4"
androidxWebkit = "1.16.0"
androidxDataStore = "1.2.1"
compose = "1.12.0-rc01"
compose-icons = "1.7.8"
compose-materia3 = "1.5.0-alpha25"
compose-material3-adaptive = "1.2.0"
compose-unstyled = "1.49.9"
lazyColumnScrollbar = "2.2.0"
appcompat = "1.7.1"
splashscreen = "1.2.0"
flexBox = "3.0.0"
autoLinkText = "2.0.2"

logbackAndroid = "3.0.0"
kotlinLogging = "8.0.4"

processPhoenix = "3.0.0"

colorpickerCompose = "1.2.0"
materialKolor = "5.0.0"
reorderable = "3.1.0"

spotless = "8.10.0"
ktlint = "1.8.0"
detekt = "2.0.0-alpha.6" # TODO switch to stable when released
composeRules = "0.6.4"

junit = "6.1.3"
androidJunit5 = "2.0.1"
mockk = "1.14.11"
turbine = "1.2.1"

benchmark = "1.5.0-beta01"
profileinstaller = "1.4.1"
uiautomator = "2.4.0"
junit4 = "4.13.2"
androidxTestExtJunit = "1.3.0"

[libraries]
android-desugar-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "androidDesugarLibs" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
android-flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexBox" }

reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kotlinx-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutable" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidxBrowser" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintLayout" }
androidx-emoji2 = { module = "androidx.emoji2:emoji2", version.ref = "androidxEmoji2" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidxExif" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-transition-ktx = { module = "androidx.transition:transition-ktx", version.ref = "androidxTransition" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidxRecyclerview" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidxViewpager2" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidxWebkit" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-datastore-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidxDataStore" }
androidx-datastore-android = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDataStore" }

compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-materia3" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose-icons" }
compose-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-icons" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-unstyled = { module = "com.composables:core", version.ref = "compose-unstyled" }
lazycolumn-scrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "lazyColumnScrollbar" }
compose-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "compose-material3-adaptive" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-annotations = { module = "io.insert-koin:koin-annotations" }

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-cache-control = { module = "io.coil-kt.coil3:coil-network-cache-control", version.ref = "coil" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-sse = { module = "com.squareup.okhttp3:okhttp-sse", version.ref = "okhttp" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver3-junit5", version.ref = "okhttp" }

colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpickerCompose" }
materialkolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
autolinktext = { module = "sh.calvin.autolinktext:autolinktext", version.ref = "autoLinkText" }

logback-android = { module = "com.github.tony19:logback-android", version.ref = "logbackAndroid" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }

process-phoenix = { module = "com.jakewharton:process-phoenix", version.ref = "processPhoenix" }

aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "about-libraries" }

detekt-compose-rules = { module = "io.nlopez.compose.rules:detekt", version.ref = "composeRules" }

androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmark" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJunit" }
junit4 = { module = "junit:junit", version.ref = "junit4" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "benchmark" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
nav-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidxNavigation" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koin-compiler-plugin" }
about-libraries-android = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "about-libraries" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "androidJunit5" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
androidx-room = { id = "androidx.room", version.ref = "androidxRoom" }  #TODO use me when working
